In [1]:
import pandas as pd

In [2]:
df=pd.read_csv(r"D:\customer-intelligence-platform\data\raw\customer_churn.csv")

In [3]:
df

,CustomerID,Age,Gender,Tenure,MonthlyCharges,Contract,PaymentMethod,TotalCharges,Churn
0,1,56,Female,68,147.58,Two year,Bank transfer,10052.03,No
1,2,69,Male,32,22.54,Month-to-month,Mailed check,686.78,No
2,3,46,Female,10,52.47,One year,Electronic check,537.88,No
3,4,32,Male,22,109.67,Month-to-month,Mailed check,2390.04,Yes
4,5,60,Female,54,130.98,Month-to-month,Credit card,7081.28,No
...,...,...,...,...,...,...,...,...,...
99995,99996,31,Male,49,26.07,Month-to-month,Electronic check,1220.50,No
99996,99997,64,Female,44,123.22,Month-to-month,Mailed check,5384.38,No
99997,99998,48,Other,32,75.37,Month-to-month,Credit card,2372.33,Yes
99998,99999,42,Female,60,114.00,Month-to-month,Mailed check,6826.55,No
99999,100000,72,Male,57,66.76,One year,Credit card,3828.60,No

In [4]:
print(df.shape)

(100000, 9)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 9 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   CustomerID      100000 non-null  int64
 1   Age             100000 non-null  int64
 2   Gender          100000 non-null  object
 3   Tenure          100000 non-null  int64
 4   MonthlyCharges  100000 non-null  float64
 5   Contract        100000 non-null  object
 6   PaymentMethod   100000 non-null  object
 7   TotalCharges    100000 non-null  float64
 8   Churn           100000 non-null  object
dtypes: float64(2), int64(3), object(4)
memory usage: 6.9+ MB

In [6]:
df.isnull().sum()

CustomerID        0
Age               0
Gender            0
Tenure            0
MonthlyCharges    0
Contract          0
PaymentMethod     0
TotalCharges      0
Churn             0
dtype: int64

In [7]:
df["Churn"].value_counts()

Churn
No     66856
Yes    33144
Name: count, dtype: int64

In [8]:
df.nunique()

CustomerID        100000
Age                   63
Gender                 3
Tenure                72
MonthlyCharges     13990
Contract               3
PaymentMethod          4
TotalCharges       92559
Churn                  2
dtype: int64

In [9]:
df.head()

,CustomerID,Age,Gender,Tenure,MonthlyCharges,Contract,PaymentMethod,TotalCharges,Churn
0,1,56,Female,68,147.58,Two year,Bank transfer,10052.03,No
1,2,69,Male,32,22.54,Month-to-month,Mailed check,686.78,No
2,3,46,Female,10,52.47,One year,Electronic check,537.88,No
3,4,32,Male,22,109.67,Month-to-month,Mailed check,2390.04,Yes
4,5,60,Female,54,130.98,Month-to-month,Credit card,7081.28,No

In [10]:
df["Gender"].value_counts()

Gender
Female    48256
Male      47787
Other      3957
Name: count, dtype: int64

In [11]:
df["Contract"].value_counts()

Contract
Month-to-month    54915
One year          25261
Two year          19824
Name: count, dtype: int64

In [12]:
df["PaymentMethod"].value_counts()

PaymentMethod
Electronic check    34892
Mailed check        25221
Credit card         20032
Bank transfer       19855
Name: count, dtype: int64

In [13]:
pd.crosstab(df["Contract"], df["Churn"])

Churn              No    Yes
Contract
Month-to-month  29348  25567
One year        21030   4231
Two year        16478   3346

In [14]:
pd.crosstab(df["PaymentMethod"], df["Churn"])

Churn                No    Yes
PaymentMethod
Bank transfer     13302   6553
Credit card       13463   6569
Electronic check  23277  11615
Mailed check      16814   8407

In [15]:
df.groupby("Churn")["Tenure"].mean()

Churn
No     39.321796
Yes    30.889784
Name: Tenure, dtype: float64

In [16]:
df.groupby("Churn")["MonthlyCharges"].mean()

Churn
No     72.845838
Yes    94.355298
Name: MonthlyCharges, dtype: float64

In [17]:
df.groupby("Churn")["Age"].mean()

Churn
No     49.102429
Yes    48.875573
Name: Age, dtype: float64

In [18]:
df.groupby("Churn")["TotalCharges"].mean()

Churn
No     2886.019353
Yes    3007.069627
Name: TotalCharges, dtype: float64

In [19]:
pd.crosstab(df["Gender"], df["Churn"])

Churn      No    Yes
Gender
Female  32405  15851
Male    31833  15954
Other    2618   1339

In [20]:
import pandas as pd

train_df = pd.read_csv("../artifacts/train.csv")
test_df = pd.read_csv("../artifacts/test.csv")

print(train_df.shape)
print(test_df.shape)

print(train_df["Churn"].value_counts(normalize=True))

print(test_df["Churn"].value_counts(normalize=True))

(80000, 9)
(20000, 9)
Churn
No     0.668562
Yes    0.331437
Name: proportion, dtype: float64
Churn
No     0.66855
Yes    0.33145
Name: proportion, dtype: float64